In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('RoughSleepers.csv')

In [17]:
df = df.set_index(list(df)[0])

In [18]:
df

,GSS Code,2019/20,2020/21,2021/22,2022/23,2023/24
Area,,,,,,
Greater London Authority,E12000007,10726,11018,8329,10053,11993
Barking & Dagenham,E09000002,85,161,131,139,159
Barnet,E09000003,178,282,173,166,216
Bexley,E09000004,42,88,93,92,106
Brent,E09000005,320,374,283,373,455
Bromley,E09000006,67,54,57,92,113
Camden,E09000007,639,630,666,719,903
City of London,E09000001,434,350,372,482,656
Croydon,E09000008,306,322,271,373,449
Ealing,E09000009,493,624,448,563,710
Enfield,E09000010,206,326,183,219,197
Greenwich,E09000011,133,213,135,196,337
Hackney,E09000012,275,350,229,246,251
Hammersmith & Fulham,E09000013,266,243,214,238,462
Haringey,E09000014,327,405,268,304,442
Harrow,E09000015,45,67,58,96,128
Havering,E09000016,71,73,69,79,55
Hillingdon,E09000017,270,282,140,167,296
Hounslow,E09000018,147,223,144,196,328
Islington,E09000019,367,388,238,337,409
Kensington & Chelsea,E09000020,316,271,193,199,226
Kingston upon Thames,E09000021,124,87,99,120,107
Lambeth,E09000022,431,581,438,623,681
Lewisham,E09000023,229,301,264,296,353
Merton,E09000024,92,109,45,63,77
Newham,E09000025,724,578,428,503,535
Redbridge,E09000026,330,380,247,248,279
Richmond,E09000027,152,115,61,86,100
Southwark,E09000028,548,567,388,435,549
Sutton,E09000029,34,18,29,30,28
Tower Hamlets,E09000030,459,400,297,460,498
Waltham Forest,E09000031,133,261,153,186,203
Wandsworth,E09000032,203,401,264,173,172
Westminster,E09000033,2757,2162,1698,2050,2102